url: "https://andreimaxim.com"
title: "Andrei Maxim"
author: "Andrei Maxim"
description: "Andrei Maxim's digital garden with writings about Ruby, Rails, HTML, CSS and JavaScript."

permalink: /posts/:slug

defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post

exclude:
  - LICENSE.md
  - README.md
