url: "https://andreimaxim.com"
title: "Andrei Maxim"
author: "Andrei Maxim"
description: "Andrei Maxim's digital garden with writings about Ruby, Rails, HTML, CSS and JavaScript."

permalink: /posts/:slug

markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true

exclude:
  - LICENSE.md
  - README.md
