url: "https://andreimaxim.com"
title: "Andrei Maxim"
author: "Andrei Maxim"

permalink: /:year/:short_month/:day/:title/

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

exclude:
  - LICENSE.md
  - README.md
