url: "https://andreimaxim.com"
title: "Thoughts on software development"
author: "Andrei Maxim"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

exclude:
  - LICENSE.md
  - README.md
