url: "https://andreimaxim.com"
title: "Andrei Maxim"
author: "Andrei Maxim"
description: "Andrei Maxim's digital garden with writings about Ruby, Rails, HTML, CSS and JavaScript."

permalink: /:year/:short_month/:day/:title/

exclude:
  - LICENSE.md
  - README.md
